website/models.py
from . import db

from flask_login import UserMixin


class Petani(db.Model, UserMixin):
  id_petani = db.Column(db.Integer,primary_key=True)
  umur_petani = db.Column(db.Integer)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()
DB_NAME = 'tanyaNi.db'

def create_app():
  app = Flask(__name__)
  app.config['SECRET_KEY'] = 'lancarkanlah project kami ya Tuhan'
  app.config['SQLALCHEMY_DATABASE_URI'] = f"sqlite:///{DB_NAME}"
  db.init_app(app)

  
  from .views import views
  app.register_blueprint(views,url_prefix='/')
  return app

website/views.py
from flask import Blueprint, render_template

views = Blueprint('views', __name__)


@views.route('/')
def home():
    return render_template('home.html')


@views.route('/errorPage')
def errorPage():
    return render_template('errorPage.html')


@views.route('/notification')
def notification():
    return render_template('notification.html')


@views.route('/buatPertanyaan')
def buatPertanyaan():
    return render_template('buatPertanyaan.html')


@views.route('/login')
def login():
    return render_template('login.html')


@views.route('/createAccount')
def createAccount():
    return render_template('create-account.html')


@views.route('/forgotPassword')
def forgotPassword():
    return render_template('forgot-password.html')


@views.route('/pertanyaanku')
def pertanyaanku():
    return render_template('pertanyaanku.html')

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
    />
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/base.css') }}"
    />
    <!-- <link rel="stylesheet" href="base.css">  -->
  </head>
  <body>
    <nav
      class="navbar navbar-expand-lg navbar-dark navbar-survival101 fixed-top"
    >
      <div class="container-fluid">
        <a class="navbar-brand" href="#">
          <!-- <h2>L O G O</h2> -->
          <img src="/static/Tanyani.png" alt="" />
        </a>

        <form class="input-group">
          <input
            class="form-control border-end-0 border rounded-0"
            type="search"
            placeholder="Cari topik yang diinginkan"
            id="example-search-input"
          />
          <span class="input-group-append">
            <button
              class="btn btn-outline-secondary bg-white border-0 rounded-0 ms-n5"
              type="button"
            >
              <i class="fa fa-search"></i>
            </button>
          </span>
        </form>

        <button
          class="navbar-toggler ml-auto custom-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div
          class="collapse navbar-collapse flex-grow-0"
          id="navbarSupportedContent"
        >
          <ul class="navbar-nav d-flex align-items-center">
            <!-- <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li> -->
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('views.notification') }}">
                <i class="fa fa-bell-o"></i>
                <!-- <span class="badge rounded-pill badge-notification bg-danger">9</span> -->
              </a>
            </li>
            <li class="nav-item image">
              <a class="" href="#">
                <img
                  src="https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745"
                  alt=""
                  width="50"
                  height="50"
                  class="rounded-circle"
                />
              </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="cek"></div>

    <div class="row test">
      <div class="col-2 border-end border-2 p-0 ckck">
        <div class="container-fluid side-bar">
          <ul class="nav align-items-center align-items-sm-start" id="menu">
            <li class="nav-item p-2 tos beranda">
              <a
                href="{{ url_for('views.home') }}"
                class="nav-link align-middle px-0 font-italic menu"
              >
                <i class="bi bi-house-door"></i>
                <span class="ms-2 d-none d-lg-inline">Beranda</span>
              </a>
            </li>
            <li class="nav-item p-2 tos pertanyaanku">
              <a
                href="{{ url_for('views.pertanyaanku') }}"
                class="nav-link px-0 align-middle font-italic menu"
              >
                <i class="bi bi-chat"></i>
                <span class="ms-2 d-none d-lg-inline">Pertanyaanku</span></a
              >
            </li>
            <li class="nav-item p-2 tos jawaban">
              <a href="#" class="nav-link px-0 align-middle font-italic menu">
                <i class="bi bi-chat-dots"></i>
                <span class="ms-2 d-none d-lg-inline">Jawaban</span>
              </a>
            </li>
            <li class="nav-item p-2 tos disimpan">
              <a href="#" class="nav-link px-0 align-middle font-italic menu">
                <i class="bi bi-bookmark"></i>
                <span class="ms-2 d-none d-lg-inline">Disimpan</span>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col border-end border-2 p-0">
        {% block content %} {% endblock %}
      </div>

      <div class="col-2 border-end border-2 p-0"></div>
    </div>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
      crossorigin="anonymous"
    ></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script> -->
  </body>
</html>

website/templates/buatPertanyaan.html
{% extends "base.html" %} {% block title %}Buat Pertanyaan{% endblock %} {%
block content %}

<meta charset="utf-8" />
<meta
  name="viewport"
  content="width=device-width, initial-scale=1, shrink-to-fit=no"
/>

<script
  src="https://cdn.tiny.cloud/1/fpssdfawcim7qf7tajsnz09q8rvkn6rabb4rohearbc71ea2/tinymce/6/tinymce.min.js"
  referrerpolicy="origin"
></script>

<script>
  tinymce.init({
    selector: "textarea#editor",
    skin: "bootstrap",
    plugins: "lists, link, image, media",
    toolbar:
      "h1 h2 bold italic strikethrough blockquote bullist numlist backcolor | link image media | removeformat help",
    menubar: false,
    statusbar: false,
  });
</script>

<style>
  /* .test .col-2{
        display: none;
    } */

  .side-bar {
    display: none;
  }

  .buat-pertanyaan h5 {
    font-size: 16px;
    font-weight: 600;
  }

  .buat-pertanyaan p,
  li {
    font-size: 14px;
    font-weight: 400;
  }

  .buat-pertanyaan .steps {
    background-color: rgb(157, 249, 157, 20%);
    color: #4ea24e;
  }

  .btn-light {
    border-color: #868881;
    color: #868881;
    margin: 0 5px;
    font-size: 1vw;
  }

  .btn-light:hover {
    border-color: #4ea24e;
  }
</style>

<div class="container-fluid p-5 buat-pertanyaan">
  <div class="card steps p-4 mb-4">
    <h5>Membuat pertanyaan yang baik</h5>
    <p>
      Anda telah siap untuk bertanya dan form ini akan memandu Anda dalam
      pengisiannya.
    </p>
    <p>Steps</p>
    <ul>
      <li>
        Usahakan judul yang Anda buat menggambarkan permasalahan yang ada.
      </li>
      <li>Deskripsikan masalah Anda secara detail.</li>
      <li>Tuliskan hasil yang Anda harapkan.</li>
      <li>Tambahkan tag untuk memudahkan pengguna lain menjawab.</li>
      <li>Review pertanyaan Anda dan unggah ke dalam forum.</li>
    </ul>
  </div>

  <div class="card judul p-4 mb-4">
    <h5>Judul</h5>
    <p>Buat judul Anda dengan spesifik.</p>
    <form class="form-group">
      <input
        type=""
        class="form-control"
        id=""
        placeholder="contoh: Bagaimana menanam pohon pisang dengan baik?"
      />
    </form>
  </div>

  <div class="card rincian p-4 mb-4">
    <h5>Rincian Permasalahan</h5>
    <p>Buat judul Anda dengan spesifik.</p>
    <form class="form-group">
      <textarea
        name=""
        id="editor"
        class="form-control"
        rows="10"
        placeholder="contoh: Bagaimana menanam pohon pisang dengan baik?"
      ></textarea>
    </form>
  </div>

  <div class="card tags p-4 mb-4">
    <h5>Tags</h5>
    <p>Tambahkan tag yang berkaitan dengan pertanyaan Anda.</p>
    <form class="form-group">
      <input type="" class="form-control" id="" placeholder="" />
    </form>
  </div>

  <div class="d-flex flex-row">
    <button type="button" class="btn btn-primary">Buat Pertanyaan</button>
    <button type="button" class="btn btn-light">Batal</button>
  </div>
</div>

{% endblock %}

website/templates/errorPage.html
{% extends "base.html" %} {% block title %}Error Page{% endblock %} {% block
content %}
<style>
  .error {
    height: 89vh;
    width: 100%;
    display: flex;
    justify-content: center;
  }

  .side-bar {
    display: none;
  }

  .error {
    padding: 0;
    margin-right: 0;
    font-family: inter;
    color: #868881;
  }

  .display-1 {
    font-size: 12vw;
    letter-spacing: 15px;
    color: #4ea24e;
  }
</style>

<div class="container-fluid error">
  <div class="row d-flex justify-content-between align-items-center">
    <div
      class="col-7 d-flex flex-column justify-content-center align-items-center"
    >
      <h1 class="display-1 fw-bold">404</h1>
      <h3 class="fw-bold text-center">OOPS! MAAF HALAMAN TIDAK DITEMUKAN</h3>
      <p class="text-center fs-6">
        Maaf, halaman yang Anda cari tidak ada. Jika menurut Anda ada yang
        rusak, laporkan masalah.
      </p>
      <div class="d-grid gap-2 d-md-block">
        <button class="btn btn-primary" type="button">Kembali ke Home</button>
        <button class="btn btn-primary" type="button">Laporkan</button>
      </div>
    </div>
    <div class="col">
      <img class="img-fluid" src="/static/GambarPetani.png" alt="" />
    </div>
  </div>
</div>
{% endblock %}

website/templates/forgot-password.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <link
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='css/forgot-password.css') }}"
    />

    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='js/center.js') }}"
    />
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <div class="col-12 bordered">
          <div class="row container">
            <h1 class="col-12">Lupa Sandi</h1>
            <h2>
              Masukkan email anda dan kami akan mengirimkan link untuk mengatur
              ulang sandi.
            </h2>
            <form class="col">
              <div class="col-12 input-container">
                <svf class="bi-envelope icon-form"></svf>
                <input
                  type="email"
                  class="myform-input"
                  placeholder="Email"
                  id="validationDefault02"
                  value=""
                  required
                />
              </div>
              <div class="col">
                <button class="btn btn-primary button-kirim" type="submit">
                  Kirim
                </button>
              </div>
              <div class="row">
                <h3 class="hal-login">
                  <a href="{{ url_for('views.login') }}">
                    <svf class="bi bi-caret-left">Kembali ke halaman login</svf>
                  </a>
                </h3>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<style>
  .beranda {
    background-color: rgb(157, 249, 157, 20%);
    font-weight: 600;
  }

  .beranda .menu {
    color: #4ea24e;
  }

  .card-header {
    padding: 1rem 1rem;
    background-color: white;
  }
  .card-header .bi,
  .card-footer .bi {
    color: #868881;
  }

  .card-header .profil .text-muted {
    font-size: 12px;
  }

  .question p,
  .key-word button {
    color: #868881;
    font-size: small;
  }

  .key-word button {
    border-color: #868881;
    color: #868881;
    margin: 0 5px;
  }

  .key-word button:hover {
    border-color: #868881;
  }

  .card-body {
    padding-left: 5vw;
    padding-right: 5vw;
  }

  .card-footer {
    padding: 1rem 1rem;
    background-color: white;
  }

  .card-footer .bi {
    font-size: medium;
    padding: 2px;
  }

  .card-footer .bi-bookmark-fill {
    border-color: #4ea24e;
  }

  .card-footer a {
    color: #868881;
    font-size: small;
  }
</style>

<div class="container-fluid flex-column justify-content-between p-5">
  <div class="text-end">
    <button type="button" class="btn btn-primary">Buat Pertanyaan</button>
  </div>

  <div class="row pt-4 d-flex flex-column">
    <div class="col pb-4">
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="profil d-flex align-items-center">
            <img
              src="https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745"
              alt=""
              width="50"
              height="50"
              class="d-block ui-w-40 rounded-circle"
            />
            <div class="media-body ps-2">
              <a href="#" data-abc="true" class="text-dark text-decoration-none"
                >Bambang</a
              >
              <div class="text-muted">15m yang lalu</div>
            </div>
          </div>
          <div class="closetab">
            <a type="button" href="#"><i class="bi bi-three-dots"></i></a>
            <a type="button" href="#"><i class="bi bi-x"></i></a>
          </div>
        </div>

        <div class="card-body d-flex flex-column">
          <div class="d-flex justify-content-between Title">
            <p class="fw-bold">Apa pupuk yang cocok untuk menanam mangga?</p>
            <div class="key-word">
              <!-- <span class="badge bg-secondary" href="#">Menanam</span> -->
              <button type="button" class="btn btn-light btn-sm">
                Menanam
              </button>
              <button type="button" class="btn btn-light btn-sm">Mangga</button>
            </div>
          </div>
          <div class="question">
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Consequatur quam ad, molestiae assumenda expedita, aut iste rem
              nisi, qui omnis voluptates corrupti reiciendis repudiandae
              dignissimos ipsa sequi tempora sed iure!
            </p>
          </div>
          <div class="image">
            <img
              class="img-fluid"
              src="https://asset.kompas.com/crops/XaytURaJTn1-yLXfwYnWzoSi82w=/62x43:942x630/750x500/data/photo/2022/06/13/62a6f4083f268.jpg"
              alt=""
            />
          </div>
        </div>
        <div class="card-footer">
          <a type="button"> <i class="bi bi-bookmark-fill"></i></a>
          <a type="button" href="#" class="text-decoration-none"
            ><i class="bi bi-chat"></i> 64+</a
          >
        </div>
      </div>
    </div>

    <div class="col pb-4">
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="profil d-flex align-items-center">
            <img
              src="https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745"
              alt=""
              width="50"
              height="50"
              class="d-block ui-w-40 rounded-circle"
            />
            <div class="media-body ps-2">
              <a href="#" data-abc="true" class="text-dark text-decoration-none"
                >Bambang</a
              >
              <div class="text-muted small">15m yang lalu</div>
            </div>
          </div>
          <div class="closetab">
            <a type="button" href="#"><i class="bi bi-three-dots"></i></a>
            <a type="button" href="#"><i class="bi bi-x"></i></a>
          </div>
        </div>

        <div class="card-body d-flex flex-column">
          <div class="d-flex justify-content-between Title">
            <p class="fw-bold">Apa pupuk yang cocok untuk menanam mangga?</p>
            <div class="key-word">
              <button type="button" class="btn btn-light btn-sm">
                Menanam
              </button>
              <button type="button" class="btn btn-light btn-sm">Mangga</button>
            </div>
          </div>
          <div class="question">
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Consequatur quam ad, molestiae assumenda expedita, aut iste rem
              nisi, qui omnis voluptates corrupti reiciendis repudiandae
              dignissimos ipsa sequi tempora sed iure!
            </p>
          </div>
          <div class="image">
            <img
              class="img-fluid"
              src="https://cdf.orami.co.id/unsafe/cdn-cas.orami.co.id/parenting/images/brokoli_7GR7GEf.width-800.jpegquality-80.jpg"
              alt=""
            />
          </div>
        </div>
        <div class="card-footer">
          <a type="button"><i class="bi bi-bookmark" id="saved"></i></a>
          <a type="button" href="#" class="text-decoration-none"
            ><i class="bi bi-chat"></i> 64+</a
          >
        </div>
      </div>
    </div>

    <div class="col pb-4">
      <div class="card">
        <div class="card-header d-flex justify-content-between">
          <div class="profil d-flex align-items-center">
            <img
              src="https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745"
              alt=""
              width="50"
              height="50"
              class="d-block ui-w-40 rounded-circle"
            />
            <div class="media-body ps-2">
              <a href="#" data-abc="true" class="text-dark text-decoration-none"
                >Bambang</a
              >
              <div class="text-muted small">15m yang lalu</div>
            </div>
          </div>
          <div class="closetab">
            <a type="button" href="#"><i class="bi bi-three-dots"></i></a>
            <a type="button" href="#"><i class="bi bi-x"></i></a>
          </div>
        </div>

        <div class="card-body d-flex flex-column">
          <div class="d-flex justify-content-between Title">
            <p class="fw-bold">Apa pupuk yang cocok untuk menanam mangga?</p>
            <div class="key-word">
              <button type="button" class="btn btn-light btn-sm">
                Menanam
              </button>
              <button type="button" class="btn btn-light btn-sm">Mangga</button>
            </div>
          </div>
          <div class="question">
            <p>
              Lorem ipsum dolor sit amet consectetur adipisicing elit.
              Consequatur quam ad, molestiae assumenda expedita, aut iste rem
              nisi, qui omnis voluptates corrupti reiciendis repudiandae
              dignissimos ipsa sequi tempora sed iure!
            </p>
          </div>
          <div class="image">
            <img
              class="img-fluid"
              src="https://assets.pikiran-rakyat.com/crop/0x0:0x0/x/photo/2020/09/17/1517003805.jpg"
              alt=""
            />
          </div>
        </div>
        <div class="card-footer">
          <a type="button"
            ><i class="bi bi-bookmark" id="saved" onclick="myFunction()"></i
          ></a>
          <a type="button" href="#" class="text-decoration-none"
            ><i class="bi bi-chat"></i> 64+</a
          >
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

website/templates/notification.html
{% extends "base.html" %} {% block title %}Notification{% endblock %} {% block
content %}
<style>
  .side-bar {
    display: none;
  }

  .notification {
    padding: 3rem 0;
  }

  .notification .title {
    padding: 0 10px;
  }

  .notification .title h5 {
    font-size: 18px;
    font-weight: 600;
  }

  .notification .title a {
    color: #868881;
    font-size: 13px;
  }

  .notification .row {
    --bs-gutter-x: 0rem;
  }

  .notification .col {
    padding: 20px 30px;
    background-color: rgb(157, 249, 157, 20%);
  }

  /* .notification .row :hover{
        background-color: rgb(157, 249, 157, 20%);
    } */

  .notification .text-muted {
    font-size: 12px;
  }

  .notification .not-text {
    padding: 0 58px;
    font-size: 12px;
    font-weight: 400;
  }
  </style>
  
  <link
    rel="stylesheet"
    href="{{ url_for('static', filename='css/notification.css') }}"
  />
  
  <script src="{{ url_for('static', filename='js/notif.js') }}"></script>

<div class="container-fluid notification">
    <div class="title d-flex justify-content-between">
        <h5>Notifikasi</h3>
        <span id="notifications"></span>
        <a href="#" class="text-decoration-none mark_all">Tandai Semua Sudah Dibaca</a>
    </div>
    <div class="row pt-2 d-flex flex-column">
        <div class="col border-top border-bottom unread">
            <div class="profil d-flex align-items-center">
                <img src="https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745" alt="" width="50" height="50" class="d-block ui-w-40 rounded-circle">
                <div class="media-body ps-2"> 
                    <div class="text-muted">1 jam yang lalu</div>
                    <span>Apa pupuk yang cocok untuk menanam mangga?</span>
                </div>
            </div>
            <span class="not-text">Parimartha menjawab pertanyaan yang Anda ajukan.</span>
        </div>
        <div class="col border-top border-bottom unread">
            <div class="profil d-flex align-items-center">
                <img src="https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745" alt="" width="50" height="50" class="d-block ui-w-40 rounded-circle">
                <div class="media-body ps-2"> 
                    <div class="text-muted">1 jam yang lalu</div>
                    <span>Apa pupuk yang cocok untuk menanam mangga?</span>
                </div>
            </div>
            <span class="not-text">Parimartha menjawab pertanyaan yang Anda ajukan.</span>
        </div>
        <div class="col border-top border-bottom unread">
            <div class="profil d-flex align-items-center">
                <img src="https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745" alt="" width="50" height="50" class="d-block ui-w-40 rounded-circle">
                <div class="media-body ps-2"> 
                    <div class="text-muted">1 jam yang lalu</div>
                    <span>Apa pupuk yang cocok untuk menanam mangga?</span>
                </div>
            </div>
            <span class="not-text">Parimartha menjawab pertanyaan yang Anda ajukan.</span>
        </div>
        <div class="col border-top border-bottom unread">
            <div class="profil d-flex align-items-center">
                <img src="https://ps.w.org/user-avatar-reloaded/assets/icon-256x256.png?rev=2540745" alt="" width="50" height="50" class="d-block ui-w-40 rounded-circle">
                <div class="media-body ps-2"> 
                    <div class="text-muted">1 jam yang lalu</div>
                    <span>Apa pupuk yang cocok untuk menanam mangga?</span>
                </div>
            </div>
            <span class="not-text">Parimartha menjawab pertanyaan yang Anda ajukan.</span>
        </div>
    </div>
</div>

{% endblock %}

website/templates/pertanyaanku.html
{% extends "base.html" %} {% block title %}Pertanyaanku{% endblock %} {% block
content %}

<style>
  .pertanyaanku {
    background-color: rgb(157, 249, 157, 20%);
    font-weight: 600;
  }

  .pertanyaanku .menu {
    color: #4ea24e;
  }

  .title {
    display: flex;
    flex-direction: row;
    justify-content: space-between;
  }

  .btn-light {
    border-color: #868881;
    color: #868881;
    margin: 0 5px;
  }

  .btn-light:hover {
    border-color: #4ea24e;
  }

  /* .btn-light:active {
    border-color: #868881;
    color: #868881;
    margin: 0 5px;
    font-size: 1vw;
  } */

  .notif .row {
    --bs-gutter-x: 0rem;
  }

  .notif .col {
    padding: 20px 30px;
  }

  .notif .answer {
    width: 15%;
  }

  .notif .text h5 {
    color: #4ea24e;
  }

  .notif .text p {
    font-size: small;
  }

  .notif .footer .text-muted {
    font-size: small;
  }

  .notif .btn-light {
    font-size: x-small;
  }
</style>

<div class="container-fluid flex-column justify-content-between p-5 pb-0">
  <div class="title">
    <h5>Semua Jawaban</h5>
    <button type="button" class="btn btn-primary">Buat Pertanyaan</button>
  </div>

  <div class="dropdown text-end pt-4 pb-4">
    <button
      class="btn btn-light dropdown-toggle"
      type="button"
      id="dropdownMenuButton1"
      data-bs-toggle="dropdown"
      aria-expanded="false"
    >
      Sort
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li><a class="dropdown-item text-muted" href="#">Terbaru</a></li>
      <li><a class="dropdown-item text-muted" href="#">Terlama</a></li>
    </ul>
  </div>
</div>

<div class="container-fluid notif p-0">
  <div class="row pt-2 d-flex flex-column">
    <div class="col border-top border-bottom unread d-flex flex-row">
      <div class="text-muted answer">
        <p>2 jawaban</p>
      </div>
      <div class="text">
        <h5>Apa pupuk yang cocok untuk menanam mangga?</h5>
        <p>
          Saya menggunakan pupuk merk X. Tapi, setelah beberapa bulan masih juga
          belum ada pertumbuhan. Apakah metode atau treatment yang saya lakukan
          salah? (lebih banyak)
        </p>
        <div class="d-flex flex-row justify-content-between footer">
          <div class="key-word">
            <!-- <span class="badge bg-secondary" href="#">Menanam</span> -->
            <button type="button" class="btn btn-light btn-sm">Menanam</button>
            <button type="button" class="btn btn-light btn-sm">Mangga</button>
          </div>
          <span class="text-muted">15m yang lalu</span>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}